### ISSUE TITLE
Plug the EPIC scraper to a parser - next steps

### ISSUE THREAD

**Issue by aalbino2** [PDI-Berlin/pdi-nomad-plugin#25]
- [x] "MBE sources" : do PLASMA sources need a Fitting.txt file ? FIll accordingly the cell
  - It doesn't. It's only for effusion cells
- [x] "MBE gas mixing".  grower: where to put it? and port number: pleonastic as it is in mbe source already?
  - should remain there
- [x] I see the Ga_Sh is always shutted off. Although we have some Ga.MV file. Can we find a meaningful dataset, now that we start having a complex series of implications in the parser? 
  - yes, we will find. Ignore the shutted off cells
- [x] problem: how to identify the correct LR from the "LR settings" (same issue as gas mixing)
  -  LR is not starting automatically with the other epic log things. 
  - I can fetch only the first matching timestamp to pick the LR settings.
- [x] check source_geometry and source length
 - fetch the flange to substarte and subtract to the source length to obtain source to substrate. (place source length and source_to_substrate quantities)
- [x] check sample status: a growth will chenage to "true" both "processed" and "grown"
  - sometimes they are epi ready and they are not process
- [x] implement search of substrates in other contexts, too. See related issue: https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/26
- [x] nest pyrometry instead of referencing it

_Originally posted by @aalbino2 in https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/7#issuecomment-2443643910_

**Comment by aalbino2** [comment]
- [ ] nest pyrometry instead of referencing it
- [ ] use an MFC threshold so understand when the gas flow starts and the growth starts
