### ISSUE TITLE
Plug EPIC scraper to a parser - further steps

### ISSUE THREAD

**Issue by aalbino2** [PDI-Berlin/pdi-nomad-plugin#31]
- [x] Parse LR.MV.txt file into LR (wait for https://github.com/PDI-Berlin/EPIC_scraper/issues/6)
- [x] fill impinging flux in Source. Check the formula:
  - 'EPIC Fitting Config File 
    Fit=AEF 	' activation energy fit: BEP=A*exp(T0/T_cell[K])
    BEP typically 1e-7mbar; FLUX typically 0.01--1 nm^-2s^-1
    Order=1 	' ignored for aef
    BEPtoFlux=4926000 ' mbar into nm^-2s^-1: FLUX=BEPtoFlux x BEP
    Coeff=4.614E00,-2.313E04 ' A, T0 (from the Fitting.txt file)
    Edit: it was filled but the value looks strange (~E-11)
- [x] "MBE sources" : do we need an ID for each source?
  - No ID for sources. The gas mixing of PLASMA source will be taken given that the growth time interval falls in the timestamp of the gas mixing lines. Problem: there are many gas mixings that match the condition mixing_date < growth_start, hence an addictional way to parse those is needed! ANswer: use the MFC flow to see when the gas is flowing. SEE https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/49
- [x] use an MFC threshold so understand when the gas flow starts and the growth starts. SEE https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/49
- [x] Shutters.txt should follow the EPIC loop naming to modulate the impinging flux
  - only impinging flux should be modulated? YES
  - which is the first line I will find in Shutters.txt? Does it align exactly with the growth start (e.g. "to GC")? It does not allign with "to GC" but tells when the growth actually starts
- [x] do not produce experiment archive during parsing. Let it be instantiated in the eln.
  If the experiment is not found by the EPIC parser, create and empty.
  Parameters to include in this class:
  - target material
  - growth ID that the growth parser will look for.
  - instantiate the steps manually and provide name and timestamp. (timestamp should be datetime.now as a default) https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/38
- [x] GC Igd.PG.MV ; GC Atmion.PG.MV ; MIG.PG.MV  (PG is Pressure Gauge)
- [x] plot in overview Substrate temp and impinging fluxes
  - edit: we cannot currently pull plot renderings from repeating sections
- [x] substrate height and substrate rotation parameters. (for later) https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/39

_Originally posted by @aalbino2 in https://github.com/PDI-Berlin/pdi-nomad-plugin/issues/25#issuecomment-2451625971_

**Comment by aalbino2** [comment]
Growth reference in experiment should be editable
